### ISSUE TITLE
reading from system audio?

### ISSUE THREAD

**Issue by mrose17** [joeferner/node-portaudio#3]
howdy! it looks like the portaudio support in nort-portaudio is for writing, not reading.

true?

if so, what's the thinking on that? i'm in the process of writing a simple node.js server that takes the system audio from my mac and makes it available to a sonos in other room, so i think being able to read audio would be handy as well?

what's your thinking? thanks!

**Comment by meltingice** [comment]
This is the exact same reason I ended up here. Would love to be able to read from portaudio in order to provide a stream to my Sonos system. Let me know if you have any luck @mrose17.

**Comment by mrose17** [comment]
i am experimenting with node-core-audio, there is some progress, but i'm not at the "declare victory part yet"
