### ISSUE TITLE
uv_work_t and uv_after_work_cb: compatibility with node >= 0.9.4

### ISSUE THREAD

**Issue by pabiagioli** [joeferner/node-portaudio#4]
This is the issue:

```
node-gyp build configure
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.9
gyp info using node@0.10.15 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/pablo/fic/portaudio-node/repo/build'
  CXX(target) Release/obj.target/portAudio/src/nodePortAudio.o
../src/nodePortAudio.cpp: In function ‘int nodePortAudioCallback(const void*, void*, long unsigned int, const PaStreamCallbackTimeInfo*, PaStreamCallbackFlags, void*)’:
../src/nodePortAudio.cpp:352:84: error: invalid conversion from ‘void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}’ to ‘uv_after_work_cb {aka void (*)(uv_work_s*, int)}’ [-fpermissive]
In file included from /home/pablo/.node-gyp/0.10.15/src/node.h:61:0,
                 from ../src/nodePortAudio.h:2,
                 from ../src/nodePortAudio.cpp:2:
/home/pablo/.node-gyp/0.10.15/deps/uv/include/uv.h:1432:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
```

There's been some changes in Node since 0.8
Here's the code for compatibility with newer node apis

https://github.com/joyent/node/wiki/Api-changes-between-v0.8-and-v0.10

The uv_after_work_cb signature has changed to take a second integer argument indicating status. For backwards compatibility, explicitly cast the 4th argument to uv_queue_work

This is the example:
https://github.com/rbranson/node-ffi/commit/fdeff41ae8b1cca31d4707d7b61253c45181b8fa

I think that changing the call like there fixes it

regards

**Comment by pabiagioli** [comment]
Also, found a missing dependency in <code>nodePortAudio.h</code>

```
#include <cstring>
```

after these 2 changes I've been able to do a "node-gyp configure build" with Ubuntu 13.04 and node 0.10.15

**Comment by joeferner** [comment]
Cool. Would you mind submitting a pull request with your changes, then I can publish a new version.

**Comment by pabiagioli** [comment]
This issue is closed with the new version https://github.com/joeferner/node-portaudio/releases/tag/v0.0.3
